# base docker-xrtc
FROM peterxu/docker-xrtc:latest

COPY scripts/routes.yml /tmp/etc/routes.yml
COPY scripts/certs/key.pem /tmp/etc/cert.key
COPY scripts/certs/cert.pem /tmp/etc/cert.pem
ADD xrtc.gen /usr/bin/xrtc

EXPOSE 6000/udp 6080/tcp 6443/tcp

ADD scripts/entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/bin/xrtc"]
