services:
    common:
        id: xrtc_id_01
        name: xrtc01
        crt_file: /tmp/etc/cert.pem
        key_file: /tmp/etc/cert.key

    route:
        name: routesvr
        addrs:
            - srt://:9527
        route:
            location: "cn;hefei"
            capacity: 100
            public_hosts: 
              - route_public_host_ip
            init_addrs:
              - route_init_addr

    ice:
        name: icesvr
        addrs:
            - tcp://:6080
            - udp://:6000
        ice:
            candidate_hosts:
              - candidate_host_ip

    rest:
        name: restsvr
        addrs:
            - http://:6443
        rest:
            servername: _
            root: /tmp/html

